# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/studio5b/studio5b.cache/wt [current_project]
set_property parent.project_path C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/studio5b/studio5b.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/studio5b/studio5b.srcs/sources_1/new/nand3_gate.vhd
  C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/studio_5/studio_5.srcs/sources_1/new/decoder.vhd
  C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/studio5b/studio5b.srcs/sources_1/new/toplevel.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/studio5b/studio5b.srcs/constrs_1/new/studio5bconstraints.xdc
set_property used_in_implementation false [get_files C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/studio5b/studio5b.srcs/constrs_1/new/studio5bconstraints.xdc]


synth_design -top toplevel -part xc7a35tcpg236-1


write_checkpoint -force -noxdef toplevel.dcp

catch { report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb }
