# Switches
set_property PACKAGE_PIN V17 [get_ports {x[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {x[2]}]
set_property PACKAGE_PIN V16 [get_ports {x[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {x[1]}]
set_property PACKAGE_PIN W16 [get_ports {x[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {x[0]}]
set_property PACKAGE_PIN W17 [get_ports {g2b_n}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {g2b_n}]
set_property PACKAGE_PIN W15 [get_ports {g2a_n}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {g2a_n}]
set_property PACKAGE_PIN V15 [get_ports {g1}]
    set_property IOSTANDARD LVCMOS33 [get_ports {g1}]
    
# LEDs
set_property PACKAGE_PIN U16 [get_ports {y[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y[7]}]
set_property PACKAGE_PIN E19 [get_ports {y[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y[6]}]
set_property PACKAGE_PIN U19 [get_ports {y[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y[5]}]
set_property PACKAGE_PIN V19 [get_ports {y[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y[4]}]
set_property PACKAGE_PIN W18 [get_ports {y[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y[3]}]
set_property PACKAGE_PIN U15 [get_ports {y[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y[2]}]
set_property PACKAGE_PIN U14 [get_ports {y[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y[1]}]
set_property PACKAGE_PIN V14 [get_ports {y[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y[0]}]